### ISSUE TITLE
Mixing roman numerals and letters

### ISSUE THREAD

**Issue by lgrn** [standardebooks/charles-darwin_the-origin-of-species#1]
Hi,

I'm not sure if this is an issue, but I thought I'd ask since it looks strange, and may cause issues if interpreted literally (which seems logical it may):

In [this commit](https://github.com/standardebooks/charles-darwin_the-origin-of-species/commit/ccf2c5692029fdc929fe1409319cbb58706f4c02), the letter V when part of an abbreviation in a name is changed from: 

`<abbr class="name">E. V.</abbr> Harcourt`

to:

`<abbr class="name">E. <span epub:type="z3998:roman">V</span>.</abbr> Harcourt`

It seems clear that this V is not the roman number five, but the letter V. Is there a reason it's marked as `type="z3998:roman"`, isn't this used for numerals?

**Comment by acabal** [comment]
Ah, this is an error introduced by `semanticate`, which tries to guess some Roman numerals but often gets tripped up in situations like these. I'll fix it shortly, thanks!
